In [2]:
#Import Depdencies
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

In [3]:
#file_path = "testingdata.csv"
file_path = "Opioid_data_2017_2020_UNCLEAN.csv"
raw_input_df = pd.read_csv(file_path)
raw_input_df.head()

Year  countycode State              county  population      deaths  \
0  2020        1001    AL  Autauga County, AL       56145  Suppressed   
1  2020        1003    AL  Baldwin County, AL      229287          41   
2  2020        1005    AL  Barbour County, AL       24589  Suppressed   
3  2020        1007    AL     Bibb County, AL       22136  Suppressed   
4  2020        1009    AL   Blount County, AL       57879  Suppressed   

    cruderate  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
0  Suppressed          98.3         45248.0                  58877.0   
1        17.9          65.0         51348.0                 233140.0   
2  Suppressed          22.8         37120.0                  25180.0   
3  Suppressed          24.8         34598.0                  22223.0   
4  Suppressed          22.8         38351.0                  59081.0   

   LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
0    583908.0      1841556.0    1611361.5         1577674.5      6242.0   
1   2063583.0      6282463.8    7153754.4         7451827.5     20189.0   
2    597512.7       902416.3     683574.2          275396.8      5548.0   
3    431652.0       971770.4     546759.2          263418.4      3549.0   
4    949215.6      2031552.9    1944734.4          862397.1      7525.0   

   PovertyRate  UnemployedPop  UnemployedRate  
0         11.2         1420.0             5.4  
1          8.9         6159.0             6.2  
2         25.5          676.0             7.8  
3         17.8          639.0             7.3  
4         13.1         1143.0             4.6

In [4]:
raw_input_df.dtypes

Year                         int64
countycode                   int64
State                       object
county                      object
population                   int64
deaths                      object
cruderate                   object
DispenseRate               float64
PersonalIncome             float64
PerCapitaPersonalIncome    float64
LessThanHS                 float64
HSDiplomaOnly              float64
SomeCollege                float64
BachelorOrHigher           float64
PovertyPop                 float64
PovertyRate                float64
UnemployedPop              float64
UnemployedRate             float64
dtype: object

In [5]:
input_df = raw_input_df.dropna().copy()
input_df = input_df.loc[(input_df["deaths"]!="Suppressed")]
input_df.head()

Year  countycode State                county  population deaths cruderate  \
1   2020        1003    AL    Baldwin County, AL      229287     41      17.9   
27  2020        1055    AL     Etowah County, AL      102371     13     12.70   
36  2020        1073    AL  Jefferson County, AL      655342    227      34.6   
44  2020        1089    AL    Madison County, AL      379453     68      17.9   
48  2020        1097    AL     Mobile County, AL      412716     46      11.1   

    DispenseRate  PersonalIncome  PerCapitaPersonalIncome  LessThanHS  \
1           65.0         51348.0                 233140.0   2063583.0   
27         102.8         39795.0                 103393.0   1412719.8   
36         139.0         58053.0                 673341.0   5898078.0   
44          87.3         56499.0                 389696.0   3035624.0   
48          98.0         42837.0                 414250.0   4993863.6   

    HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  PovertyRate  \
1       6282463.8    7153754.4         7451827.5     20189.0          8.9   
27      3460139.8    3521562.4         1842678.0     15650.0         15.6   
36     17301028.8   19594725.8        22740367.4     92310.0         14.4   
44      7285497.6   10814410.5        16809767.9     39100.0         10.5   
48     14114887.2   12257665.2         9863912.4     71398.0         17.6   

    UnemployedPop  UnemployedRate  
1          6159.0             6.2  
27         3505.0             8.5  
36        21947.0             6.9  
44         9761.0             5.1  
48        16931.0             8.7

In [6]:
print(len(input_df))
test_df = input_df.loc[(input_df['cruderate']!='Unreliable')]
print(len(test_df))

3065
3065


In [8]:
cleaned_test_df = test_df.astype({"cruderate":"float64"}, copy=True)
#cleaned_test_df["PovertyPop"] = cleaned_test_df["PovertyPop"].str.replace(",","")
#cleaned_test_df["UnemployedPop"] = cleaned_test_df["UnemployedPop"].str.replace(",","")
#cleaned_test_df = cleaned_test_df.astype({"PovertyPop":"float64","UnemployedPop":"float64"})
cleaned_test_df["LessThanHS"] = cleaned_test_df["LessThanHS"]/100
cleaned_test_df["HSDiplomaOnly"] = cleaned_test_df["HSDiplomaOnly"]/100
cleaned_test_df["SomeCollege"] = cleaned_test_df["SomeCollege"]/100
cleaned_test_df["BachelorOrHigher"] = cleaned_test_df["BachelorOrHigher"]/100
cleaned_test_df.head()

Year  countycode State                county  population deaths  \
1   2020        1003    AL    Baldwin County, AL      229287     41   
27  2020        1055    AL     Etowah County, AL      102371     13   
36  2020        1073    AL  Jefferson County, AL      655342    227   
44  2020        1089    AL    Madison County, AL      379453     68   
48  2020        1097    AL     Mobile County, AL      412716     46   

    cruderate  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
1        17.9          65.0         51348.0                 233140.0   
27       12.7         102.8         39795.0                 103393.0   
36       34.6         139.0         58053.0                 673341.0   
44       17.9          87.3         56499.0                 389696.0   
48       11.1          98.0         42837.0                 414250.0   

    LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
1    20635.830      62824.638    71537.544         74518.275     20189.0   
27   14127.198      34601.398    35215.624         18426.780     15650.0   
36   58980.780     173010.288   195947.258        227403.674     92310.0   
44   30356.240      72854.976   108144.105        168097.679     39100.0   
48   49938.636     141148.872   122576.652         98639.124     71398.0   

    PovertyRate  UnemployedPop  UnemployedRate  
1           8.9         6159.0             6.2  
27         15.6         3505.0             8.5  
36         14.4        21947.0             6.9  
44         10.5         9761.0             5.1  
48         17.6        16931.0             8.7

In [9]:
data2020 =  cleaned_test_df.loc[(test_df["Year"]==2020),"cruderate"]
quartile75_2020 = np.percentile(data2020, 75)
print(quartile75_2020)

36.6


In [10]:
data2019 =  cleaned_test_df.loc[(test_df["Year"]==2019),"cruderate"]
quartile75_2019 = np.percentile(data2019, 75)
print(quartile75_2019)

27.3


In [11]:
data2018 =  cleaned_test_df.loc[(test_df["Year"]==2018),"cruderate"]
quartile75_2018 = np.percentile(data2018, 75)
print(quartile75_2018)

28.299999999999997


In [12]:
data2017 =  cleaned_test_df.loc[(test_df["Year"]==2017),"cruderate"]
quartile75_2017 = np.percentile(data2017, 75)
print(quartile75_2017)

29.4


In [13]:
type(quartile75_2017)

numpy.float64

In [14]:
print(cleaned_test_df["Year"].values)

[2020 2020 2020 ... 2017 2017 2017]


In [15]:
solution_series = []
year_series = cleaned_test_df["Year"].values
test1 = cleaned_test_df["cruderate"].values
#print(year_series[0])
for i in range(len(year_series)):
    if year_series[i]==2017:
        if test1[i]>=quartile75_2017:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2018:
        if test1[i]>=quartile75_2018:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2019:
        if test1[i]>=quartile75_2019:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2020:
        if test1[i]>=quartile75_2020:
            solution_series.append(1)
        else:
            solution_series.append(0)

#print(solution_series)

In [16]:
cleaned_test_df["Class"] = solution_series
cleaned_test_df.head()
print(cleaned_test_df["Class"].value_counts())

0    2294
1     771
Name: Class, dtype: int64


In [50]:
X = cleaned_test_df.copy()
X = X.drop(["State","county","countycode","Year","Class","PovertyRate","UnemployedRate","cruderate","deaths"],axis=1)
X.head()

population  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
1       229287          65.0         51348.0                 233140.0   
27      102371         102.8         39795.0                 103393.0   
36      655342         139.0         58053.0                 673341.0   
44      379453          87.3         56499.0                 389696.0   
48      412716          98.0         42837.0                 414250.0   

    LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
1    20635.830      62824.638    71537.544         74518.275     20189.0   
27   14127.198      34601.398    35215.624         18426.780     15650.0   
36   58980.780     173010.288   195947.258        227403.674     92310.0   
44   30356.240      72854.976   108144.105        168097.679     39100.0   
48   49938.636     141148.872   122576.652         98639.124     71398.0   

    UnemployedPop  
1          6159.0  
27         3505.0  
36        21947.0  
44         9761.0  
48        16931.0

In [51]:
y = cleaned_test_df["Class"]
test_y = cleaned_test_df["Class"].ravel()
print(type(y))
print(type(test_y))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [52]:
X_train, X_test,y_train, y_test = train_test_split(X,y,random_state = 94)

In [53]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [54]:
rf_model = RandomForestClassifier(n_estimators=128, random_state=94) 

In [55]:
rf_model = rf_model.fit(X_train_scaled, y_train)

In [56]:
predictions = rf_model.predict(X_test_scaled)

In [57]:
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0          579           17
Actual 1           69          102

In [58]:
acc_score = accuracy_score(y_test, predictions)

In [59]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          579           17
Actual 1           69          102

Accuracy Score : 0.8878748370273793
Classification Report
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       596
           1       0.86      0.60      0.70       171

    accuracy                           0.89       767
   macro avg       0.88      0.78      0.82       767
weighted avg       0.89      0.89      0.88       767



In [60]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.15896594, 0.08270636, 0.07887408, 0.13239609, 0.07690283,
       0.09285297, 0.08790893, 0.08642849, 0.08638042, 0.1165839 ])

In [61]:
#I just want to try out SMOTEENN
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)

In [62]:
scaler2 = StandardScaler()
X_scaler2 = scaler2.fit(X_resampled)
X_train2_scaled = X_scaler2.transform(X_resampled)
X_test2_scaled = X_scaler2.transform(X_test)

In [63]:
rf_model2 = RandomForestClassifier(n_estimators=128, random_state=94) 

In [64]:
rf_model2 = rf_model2.fit(X_train2_scaled, y_resampled)

In [65]:
predictions2 = rf_model2.predict(X_test_scaled)

In [66]:
cm2 = confusion_matrix(y_test, predictions2)
cm2_df = pd.DataFrame(
    cm2, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm2_df

Predicted 0  Predicted 1
Actual 0          460          136
Actual 1           57          114

In [67]:
acc_score2 = accuracy_score(y_test, predictions2)

In [68]:
# Displaying results
print("Confusion Matrix")
display(cm2_df)
print(f"Accuracy Score : {acc_score2}")
print("Classification Report")
print(classification_report(y_test, predictions2))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          460          136
Actual 1           57          114

Accuracy Score : 0.7483702737940026
Classification Report
              precision    recall  f1-score   support

           0       0.89      0.77      0.83       596
           1       0.46      0.67      0.54       171

    accuracy                           0.75       767
   macro avg       0.67      0.72      0.68       767
weighted avg       0.79      0.75      0.76       767



In [69]:
# Calculate feature importance in the Random Forest model.
importances2 = rf_model2.feature_importances_
importances2

array([0.2002794 , 0.07516354, 0.07264491, 0.1571447 , 0.07094668,
       0.09233952, 0.07237844, 0.06937944, 0.08729178, 0.10243159])