In [1]:
#Import Depdencies
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

In [39]:
#file_path = "testingdata.csv"
file_path = "FINAL_opioid_data_UNCLEAN2.csv"
raw_input_df = pd.read_csv(file_path)
raw_input_df.head()

Year  countycode State              county  population      deaths  \
0  2020        1001    AL  Autauga County, AL       56145  Suppressed   
1  2020        1003    AL  Baldwin County, AL      229287          41   
2  2020        1005    AL  Barbour County, AL       24589  Suppressed   
3  2020        1007    AL     Bibb County, AL       22136  Suppressed   
4  2020        1009    AL   Blount County, AL       57879  Suppressed   

    cruderate  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
0  Suppressed          98.3         45248.0                  58877.0   
1       17.90          65.0         51348.0                 233140.0   
2  Suppressed          22.8         37120.0                  25180.0   
3  Suppressed          24.8         34598.0                  22223.0   
4  Suppressed          22.8         38351.0                  59081.0   

   LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
0     5839.08       18415.56     16113.62          15776.75      6242.0   
1    20635.83       62824.64     71537.54          74518.28     20189.0   
2     5975.13        9024.16      6835.74           2753.97      5548.0   
3     4316.52        9717.70      5467.59           2634.18      3549.0   
4     9492.16       20315.53     19447.34           8623.97      7525.0   

   PovertyRate  UnemployedPop  UnemployedRate  
0         11.2         1420.0             5.4  
1          8.9         6159.0             6.2  
2         25.5          676.0             7.8  
3         17.8          639.0             7.3  
4         13.1         1143.0             4.6

In [40]:
raw_input_df.dtypes

Year                         int64
countycode                   int64
State                       object
county                      object
population                   int64
deaths                      object
cruderate                   object
DispenseRate               float64
PersonalIncome             float64
PerCapitaPersonalIncome    float64
LessThanHS                 float64
HSDiplomaOnly              float64
SomeCollege                float64
BachelorOrHigher           float64
PovertyPop                 float64
PovertyRate                float64
UnemployedPop              float64
UnemployedRate             float64
dtype: object

In [41]:
input_df = raw_input_df.dropna().copy()
input_df = input_df.loc[(input_df["deaths"]!="Suppressed")]
input_df.head()

Year  countycode State                county  population deaths cruderate  \
1   2020        1003    AL    Baldwin County, AL      229287     41     17.90   
27  2020        1055    AL     Etowah County, AL      102371     13     12.70   
36  2020        1073    AL  Jefferson County, AL      655342    227     34.60   
44  2020        1089    AL    Madison County, AL      379453     68     17.90   
48  2020        1097    AL     Mobile County, AL      412716     46     11.10   

    DispenseRate  PersonalIncome  PerCapitaPersonalIncome  LessThanHS  \
1           65.0         51348.0                 233140.0    20635.83   
27         102.8         39795.0                 103393.0    14127.20   
36         139.0         58053.0                 673341.0    58980.78   
44          87.3         56499.0                 389696.0    30356.24   
48          98.0         42837.0                 414250.0    49938.64   

    HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  PovertyRate  \
1        62824.64     71537.54          74518.28     20189.0          8.9   
27       34601.40     35215.62          18426.78     15650.0         15.6   
36      173010.29    195947.26         227403.67     92310.0         14.4   
44       72854.98    108144.11         168097.68     39100.0         10.5   
48      141148.87    122576.65          98639.12     71398.0         17.6   

    UnemployedPop  UnemployedRate  
1          6159.0             6.2  
27         3505.0             8.5  
36        21947.0             6.9  
44         9761.0             5.1  
48        16931.0             8.7

In [42]:
print(len(input_df))
test_df = input_df.loc[(input_df['cruderate']!='Unreliable')]
print(len(test_df))

3056
3056


In [72]:
cleaned_test_df = test_df.astype({"cruderate":"float64"}, copy=True)
#cleaned_test_df["PovertyPop"] = cleaned_test_df["PovertyPop"].str.replace(",","")
#cleaned_test_df["UnemployedPop"] = cleaned_test_df["UnemployedPop"].str.replace(",","")
#cleaned_test_df = cleaned_test_df.astype({"PovertyPop":"float64","UnemployedPop":"float64"})
cleaned_test_df["LessThanHS"] = cleaned_test_df["LessThanHS"]
cleaned_test_df["HSDiplomaOnly"] = cleaned_test_df["HSDiplomaOnly"]
cleaned_test_df["SomeCollege"] = cleaned_test_df["SomeCollege"]
cleaned_test_df["BachelorOrHigher"] = cleaned_test_df["BachelorOrHigher"]
cleaned_test_df.head()

Year  countycode State                county  population deaths  \
1   2020        1003    AL    Baldwin County, AL      229287     41   
27  2020        1055    AL     Etowah County, AL      102371     13   
36  2020        1073    AL  Jefferson County, AL      655342    227   
44  2020        1089    AL    Madison County, AL      379453     68   
48  2020        1097    AL     Mobile County, AL      412716     46   

    cruderate  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
1        17.9          65.0         51348.0                 233140.0   
27       12.7         102.8         39795.0                 103393.0   
36       34.6         139.0         58053.0                 673341.0   
44       17.9          87.3         56499.0                 389696.0   
48       11.1          98.0         42837.0                 414250.0   

    LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
1     20635.83       62824.64     71537.54          74518.28     20189.0   
27    14127.20       34601.40     35215.62          18426.78     15650.0   
36    58980.78      173010.29    195947.26         227403.67     92310.0   
44    30356.24       72854.98    108144.11         168097.68     39100.0   
48    49938.64      141148.87    122576.65          98639.12     71398.0   

    PovertyRate  UnemployedPop  UnemployedRate  
1           8.9         6159.0             6.2  
27         15.6         3505.0             8.5  
36         14.4        21947.0             6.9  
44         10.5         9761.0             5.1  
48         17.6        16931.0             8.7

In [73]:
data2020 =  cleaned_test_df.loc[(test_df["Year"]==2020),"cruderate"]
quartile75_2020 = np.percentile(data2020, 75)
print(quartile75_2020)

36.5


In [74]:
data2019 =  cleaned_test_df.loc[(test_df["Year"]==2019),"cruderate"]
quartile75_2019 = np.percentile(data2019, 75)
print(quartile75_2019)

27.317500000000003


In [75]:
data2018 =  cleaned_test_df.loc[(test_df["Year"]==2018),"cruderate"]
quartile75_2018 = np.percentile(data2018, 75)
print(quartile75_2018)

28.4


In [76]:
data2017 =  cleaned_test_df.loc[(test_df["Year"]==2017),"cruderate"]
quartile75_2017 = np.percentile(data2017, 75)
print(quartile75_2017)

29.4


In [77]:
type(quartile75_2017)

numpy.float64

In [78]:
print(cleaned_test_df["Year"].values)

[2020 2020 2020 ... 2017 2017 2017]


In [79]:
solution_series = []
year_series = cleaned_test_df["Year"].values
test1 = cleaned_test_df["cruderate"].values
#print(year_series[0])
for i in range(len(year_series)):
    if year_series[i]==2017:
        if test1[i]>=quartile75_2017:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2018:
        if test1[i]>=quartile75_2018:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2019:
        if test1[i]>=quartile75_2019:
            solution_series.append(1)
        else:
            solution_series.append(0)
    elif year_series[i]==2020:
        if test1[i]>=quartile75_2020:
            solution_series.append(1)
        else:
            solution_series.append(0)

#print(solution_series)

In [80]:
cleaned_test_df["Class"] = solution_series
cleaned_test_df.head()
print(cleaned_test_df["Class"].value_counts())

0    2287
1     769
Name: Class, dtype: int64


In [81]:
X = cleaned_test_df.copy()
X = X.drop(["State","county","countycode","Year","Class","PovertyRate","UnemployedRate","cruderate","deaths"],axis=1)
X.head()

population  DispenseRate  PersonalIncome  PerCapitaPersonalIncome  \
1       229287          65.0         51348.0                 233140.0   
27      102371         102.8         39795.0                 103393.0   
36      655342         139.0         58053.0                 673341.0   
44      379453          87.3         56499.0                 389696.0   
48      412716          98.0         42837.0                 414250.0   

    LessThanHS  HSDiplomaOnly  SomeCollege  BachelorOrHigher  PovertyPop  \
1     20635.83       62824.64     71537.54          74518.28     20189.0   
27    14127.20       34601.40     35215.62          18426.78     15650.0   
36    58980.78      173010.29    195947.26         227403.67     92310.0   
44    30356.24       72854.98    108144.11         168097.68     39100.0   
48    49938.64      141148.87    122576.65          98639.12     71398.0   

    UnemployedPop  
1          6159.0  
27         3505.0  
36        21947.0  
44         9761.0  
48        16931.0

In [82]:
y = cleaned_test_df["Class"]
test_y = cleaned_test_df["Class"].ravel()
print(type(y))
print(type(test_y))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [83]:
X_train, X_test,y_train, y_test = train_test_split(X,y,random_state = 94)

In [84]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [85]:
rf_model = RandomForestClassifier(n_estimators=128, random_state=94) 

In [86]:
rf_model = rf_model.fit(X_train_scaled, y_train)

In [87]:
predictions = rf_model.predict(X_test_scaled)

In [88]:
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

#cm_df

In [89]:
acc_score = accuracy_score(y_test, predictions)

In [90]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          536           39
Actual 1           81          108

Accuracy Score : 0.8429319371727748
Classification Report
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       575
           1       0.73      0.57      0.64       189

    accuracy                           0.84       764
   macro avg       0.80      0.75      0.77       764
weighted avg       0.84      0.84      0.84       764



In [91]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.1703424 , 0.07165623, 0.07183777, 0.13533813, 0.08734406,
       0.09766407, 0.08887849, 0.08749299, 0.07577779, 0.11366806])

In [92]:
#I just want to try out SMOTEENN
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)

In [93]:
scaler2 = StandardScaler()
X_scaler2 = scaler2.fit(X_resampled)
X_train2_scaled = X_scaler2.transform(X_resampled)
X_test2_scaled = X_scaler2.transform(X_test)

In [94]:
rf_model2 = RandomForestClassifier(n_estimators=128, random_state=94) 

In [95]:
rf_model2 = rf_model2.fit(X_train2_scaled, y_resampled)

In [96]:
predictions2 = rf_model2.predict(X_test_scaled)

In [97]:
cm2 = confusion_matrix(y_test, predictions2)
cm2_df = pd.DataFrame(
    cm2, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

#cm2_df

In [98]:
acc_score2 = accuracy_score(y_test, predictions2)

In [99]:
# Displaying results
print("Confusion Matrix")
display(cm2_df)
print(f"Accuracy Score : {acc_score2}")
print("Classification Report")
print(classification_report(y_test, predictions2))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          426          149
Actual 1           58          131

Accuracy Score : 0.7290575916230366
Classification Report
              precision    recall  f1-score   support

           0       0.88      0.74      0.80       575
           1       0.47      0.69      0.56       189

    accuracy                           0.73       764
   macro avg       0.67      0.72      0.68       764
weighted avg       0.78      0.73      0.74       764



In [100]:
# Calculate feature importance in the Random Forest model.
importances2 = rf_model2.feature_importances_
importances2

array([0.18898751, 0.06557377, 0.07363999, 0.14612253, 0.08553225,
       0.09761144, 0.09095363, 0.08725005, 0.06833221, 0.09599663])